# Generated by Django 6.0.7 on 2026-07-12 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('flagged', 'Flagged'), ('skipped', 'Skipped'), ('modified', 'Modified')], default='ok', max_length=20)),
            ],
            options={
                'db_table': 'import_rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Entry'), ('missing_field', 'Missing Required Field'), ('settlement', 'Settlement as Expense'), ('percentage_mismatch', 'Percentage Sum ≠ 100%'), ('name_variant', 'Name Variant Detected'), ('currency_missing', 'Missing Currency'), ('multi_currency', 'Multi-Currency Entry'), ('date_anomaly', 'Date Anomaly'), ('zero_amount', 'Zero Amount'), ('negative_amount', 'Negative Amount (Refund)'), ('unknown_participant', 'Unknown Participant'), ('membership_violation', 'Membership Temporal Violation'), ('split_mismatch', 'Split Type/Details Mismatch'), ('name_casing', 'Name Casing Inconsistency')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('auto_resolution', models.TextField(blank=True, default='')),
                ('user_resolution', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='importer.importrow')),
            ],
            options={
                'db_table': 'import_anomalies',
                'ordering': ['-severity', 'row__row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('exchange_rate_usd', models.DecimalField(decimal_places=2, default=85.0, help_text='USD to INR exchange rate used for this import', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='expenses.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importrow',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importsession'),
        ),
        migrations.AlterUniqueTogether(
            name='importrow',
            unique_together={('session', 'row_number')},
        ),
    ]
